import { useQuery } from '@tanstack/react-query'
import { apiRequest } from '../../shared/api/client'
import { ErrorState, LoadingState, Page } from '../../shared/ui/Page'

interface UserRow { readonly id: string; readonly email: string; readonly display_name: string; readonly locale: string; readonly status: string; readonly role: string; readonly created_at: string }
interface DeliveryRow { readonly id: string; readonly status: string; readonly attempts: number; readonly error_code: string | null; readonly attempted_at: string | null; readonly created_at: string }
interface AuditRow { readonly id: string; readonly action: string; readonly entity_type: string; readonly actor_user_id: string; readonly created_at: string }

function DataTable({ headers, rows }: { readonly headers: readonly string[]; readonly rows: readonly (readonly string[])[] }) { return <div className="overflow-x-auto rounded-xl border border-zinc-800"><table className="w-full text-left text-sm"><thead className="bg-zinc-900 text-zinc-400"><tr>{headers.map(item => <th key={item} className="p-4">{item}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index} className="border-t border-zinc-800">{row.map((cell, cellIndex) => <td key={cellIndex} className="p-4">{cell}</td>)}</tr>)}</tbody></table></div> }

export function UsersPage() { const query = useQuery({ queryKey: ['admin-users'], queryFn: () => apiRequest<readonly UserRow[]>('/admin/users') }); if (query.isPending) return <LoadingState />; if (query.error) return <ErrorState error={query.error} />; return <Page title="Users" eyebrow="Operations"><DataTable headers={['Name', 'Email', 'Locale', 'Role', 'Status']} rows={query.data.map(item => [item.display_name, item.email, item.locale, item.role, item.status])} /></Page> }
export function DeliveriesPage() { const query = useQuery({ queryKey: ['deliveries'], queryFn: () => apiRequest<readonly DeliveryRow[]>('/admin/deliveries') }); if (query.isPending) return <LoadingState />; if (query.error) return <ErrorState error={query.error} />; return <Page title="Alert deliveries" eyebrow="Push health"><DataTable headers={['Created', 'Status', 'Attempts', 'Error']} rows={query.data.map(item => [new Date(item.created_at).toLocaleString(), item.status, String(item.attempts), item.error_code ?? '—'])} /></Page> }
export function AuditLogsPage() { const query = useQuery({ queryKey: ['audit'], queryFn: () => apiRequest<readonly AuditRow[]>('/admin/audit-logs?limit=100') }); if (query.isPending) return <LoadingState />; if (query.error) return <ErrorState error={query.error} />; return <Page title="Audit logs" eyebrow="Security"><DataTable headers={['Time', 'Action', 'Entity', 'Actor']} rows={query.data.map(item => [new Date(item.created_at).toLocaleString(), item.action, item.entity_type, item.actor_user_id])} /></Page> }
