"""add favorites and alert uniqueness.

Revision ID: 5dd3800faa24
Revises: 72b981c290e7
Create Date: 2026-07-12 21:19:02.748031
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5dd3800faa24"
down_revision: str | None = "72b981c290e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "favorites",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "target_type IN ('event', 'organization', 'athlete')",
            name=op.f("ck_favorites_favorite_target_type"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_favorites_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_favorites")),
        sa.UniqueConstraint(
            "user_id", "target_type", "target_id", name=op.f("uq_favorites_user_id")
        ),
    )
    op.create_index(
        op.f("ix_favorites_target_id"), "favorites", ["target_id"], unique=False
    )
    op.create_index(
        op.f("ix_favorites_target_type"), "favorites", ["target_type"], unique=False
    )
    op.create_index(
        op.f("ix_favorites_user_id"), "favorites", ["user_id"], unique=False
    )
    op.create_unique_constraint(
        op.f("uq_alerts_user_id"),
        "alerts",
        ["user_id", "fight_id", "trigger_type", "lead_minutes"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_alerts_user_id"), "alerts", type_="unique")
    op.drop_index(op.f("ix_favorites_user_id"), table_name="favorites")
    op.drop_index(op.f("ix_favorites_target_type"), table_name="favorites")
    op.drop_index(op.f("ix_favorites_target_id"), table_name="favorites")
    op.drop_table("favorites")
    # ### end Alembic commands ###
