"""create initial domain schema.

Revision ID: da8dd76f43b0
Revises:
Create Date: 2026-07-12 20:55:09.982333
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "da8dd76f43b0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "athletes",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("nickname", sa.String(length=160), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column(
            "external_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_athletes")),
    )
    op.create_index(op.f("ix_athletes_name"), "athletes", ["name"], unique=False)
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_index(
        op.f("ix_organizations_active"), "organizations", ["active"], unique=False
    )
    op.create_index(
        op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("locale", sa.String(length=16), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_actor_user_id"),
        "audit_logs",
        ["actor_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False
    )
    op.create_table(
        "devices",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("push_token", sa.Text(), nullable=False),
        sa.Column("app_version", sa.String(length=32), nullable=False),
        sa.Column("notifications_enabled", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_devices_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("push_token", name=op.f("uq_devices_push_token")),
    )
    op.create_index(op.f("ix_devices_user_id"), "devices", ["user_id"], unique=False)
    op.create_table(
        "events",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("venue", sa.String(length=200), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("scheduled_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actual_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "DELAYED",
                "LIVE",
                "PAUSED",
                "COMPLETED",
                "CANCELLED",
                name="event_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "provider_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_events_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint("slug", name=op.f("uq_events_slug")),
    )
    op.create_index(
        op.f("ix_events_organization_id"), "events", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_events_scheduled_start_at"),
        "events",
        ["scheduled_start_at"],
        unique=False,
    )
    op.create_index(op.f("ix_events_status"), "events", ["status"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("plan", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("external_customer_id", sa.String(length=160), nullable=False),
        sa.Column("external_subscription_id", sa.String(length=160), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_subscriptions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint(
            "external_subscription_id",
            name=op.f("uq_subscriptions_external_subscription_id"),
        ),
    )
    op.create_index(
        op.f("ix_subscriptions_status"), "subscriptions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False
    )
    op.create_table(
        "event_changes",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column(
            "before_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("after_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_event_changes_actor_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_event_changes_event_id_events")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_changes")),
    )
    op.create_index(
        op.f("ix_event_changes_entity_id"), "event_changes", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_event_changes_event_id"), "event_changes", ["event_id"], unique=False
    )
    op.create_table(
        "fights",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("red_athlete_id", sa.UUID(), nullable=False),
        sa.Column("blue_athlete_id", sa.UUID(), nullable=False),
        sa.Column("weight_class", sa.String(length=80), nullable=True),
        sa.Column("bout_type", sa.String(length=80), nullable=True),
        sa.Column("scheduled_order", sa.Integer(), nullable=False),
        sa.Column("current_order", sa.Integer(), nullable=False),
        sa.Column("rounds_scheduled", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "NEXT",
                "WALKOUTS",
                "LIVE",
                "PAUSED",
                "COMPLETED",
                "CANCELLED",
                "NO_CONTEST",
                name="fight_status",
            ),
            nullable=False,
        ),
        sa.Column("actual_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result_method", sa.String(length=120), nullable=True),
        sa.Column("winner_athlete_id", sa.UUID(), nullable=True),
        sa.Column(
            "provider_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["blue_athlete_id"],
            ["athletes.id"],
            name=op.f("fk_fights_blue_athlete_id_athletes"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_fights_event_id_events")
        ),
        sa.ForeignKeyConstraint(
            ["red_athlete_id"],
            ["athletes.id"],
            name=op.f("fk_fights_red_athlete_id_athletes"),
        ),
        sa.ForeignKeyConstraint(
            ["winner_athlete_id"],
            ["athletes.id"],
            name=op.f("fk_fights_winner_athlete_id_athletes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fights")),
        sa.UniqueConstraint(
            "event_id", "current_order", name=op.f("uq_fights_event_id")
        ),
    )
    op.create_index(
        op.f("ix_fights_current_order"), "fights", ["current_order"], unique=False
    )
    op.create_index(op.f("ix_fights_event_id"), "fights", ["event_id"], unique=False)
    op.create_index(op.f("ix_fights_status"), "fights", ["status"], unique=False)
    op.create_table(
        "alerts",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("fight_id", sa.UUID(), nullable=False),
        sa.Column("trigger_type", sa.String(length=64), nullable=False),
        sa.Column("lead_minutes", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fight_id"], ["fights.id"], name=op.f("fk_alerts_fight_id_fights")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_alerts_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_index(op.f("ix_alerts_fight_id"), "alerts", ["fight_id"], unique=False)
    op.create_index(
        "ix_alerts_fight_status", "alerts", ["fight_id", "status"], unique=False
    )
    op.create_index(op.f("ix_alerts_status"), "alerts", ["status"], unique=False)
    op.create_index(op.f("ix_alerts_user_id"), "alerts", ["user_id"], unique=False)
    op.create_table(
        "fight_state_events",
        sa.Column("fight_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "SCHEDULED",
                "NEXT",
                "WALKOUTS",
                "LIVE",
                "PAUSED",
                "COMPLETED",
                "CANCELLED",
                "NO_CONTEST",
                name="fight_status",
            ),
            nullable=False,
        ),
        sa.Column("round_number", sa.Integer(), nullable=True),
        sa.Column("clock_seconds", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_fight_state_events_event_id_events"),
        ),
        sa.ForeignKeyConstraint(
            ["fight_id"],
            ["fights.id"],
            name=op.f("fk_fight_state_events_fight_id_fights"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fight_state_events")),
    )
    op.create_index(
        op.f("ix_fight_state_events_event_id"),
        "fight_state_events",
        ["event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fight_state_events_fight_id"),
        "fight_state_events",
        ["fight_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fight_state_events_occurred_at"),
        "fight_state_events",
        ["occurred_at"],
        unique=False,
    )
    op.create_table(
        "predictions",
        sa.Column("fight_id", sa.UUID(), nullable=False),
        sa.Column("predicted_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("earliest_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latest_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confidence_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("factors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence_score >= 0 AND confidence_score <= 1",
            name=op.f("ck_predictions_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["fight_id"], ["fights.id"], name=op.f("fk_predictions_fight_id_fights")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_predictions")),
    )
    op.create_index(
        op.f("ix_predictions_fight_id"), "predictions", ["fight_id"], unique=False
    )
    op.create_table(
        "alert_deliveries",
        sa.Column("alert_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alerts.id"],
            name=op.f("fk_alert_deliveries_alert_id_alerts"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_alert_deliveries_device_id_devices"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_deliveries")),
        sa.UniqueConstraint(
            "idempotency_key", name=op.f("uq_alert_deliveries_idempotency_key")
        ),
    )
    op.create_index(
        op.f("ix_alert_deliveries_alert_id"),
        "alert_deliveries",
        ["alert_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alert_deliveries_device_id"),
        "alert_deliveries",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alert_deliveries_status"), "alert_deliveries", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alert_deliveries_status"), table_name="alert_deliveries")
    op.drop_index(op.f("ix_alert_deliveries_device_id"), table_name="alert_deliveries")
    op.drop_index(op.f("ix_alert_deliveries_alert_id"), table_name="alert_deliveries")
    op.drop_table("alert_deliveries")
    op.drop_index(op.f("ix_predictions_fight_id"), table_name="predictions")
    op.drop_table("predictions")
    op.drop_index(
        op.f("ix_fight_state_events_occurred_at"), table_name="fight_state_events"
    )
    op.drop_index(
        op.f("ix_fight_state_events_fight_id"), table_name="fight_state_events"
    )
    op.drop_index(
        op.f("ix_fight_state_events_event_id"), table_name="fight_state_events"
    )
    op.drop_table("fight_state_events")
    op.drop_index(op.f("ix_alerts_user_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_status"), table_name="alerts")
    op.drop_index("ix_alerts_fight_status", table_name="alerts")
    op.drop_index(op.f("ix_alerts_fight_id"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_fights_status"), table_name="fights")
    op.drop_index(op.f("ix_fights_event_id"), table_name="fights")
    op.drop_index(op.f("ix_fights_current_order"), table_name="fights")
    op.drop_table("fights")
    op.drop_index(op.f("ix_event_changes_event_id"), table_name="event_changes")
    op.drop_index(op.f("ix_event_changes_entity_id"), table_name="event_changes")
    op.drop_table("event_changes")
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_status"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_events_status"), table_name="events")
    op.drop_index(op.f("ix_events_scheduled_start_at"), table_name="events")
    op.drop_index(op.f("ix_events_organization_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_devices_user_id"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_active"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_athletes_name"), table_name="athletes")
    op.drop_table("athletes")
    op.execute("DROP TYPE IF EXISTS fight_status")
    op.execute("DROP TYPE IF EXISTS event_status")
    # ### end Alembic commands ###
